anycast_mac_address: 00:00:00:00:01:02
ipdhcp:
  dhcp: [ ]
  max_hop_count: 3
  source_lb_interface: 2
  vrf_name: Vrf1
ipdhcp_loopback_ip: '{{ host_data[inventory_hostname].ipdhcp_loopback_ip }}'
loopback1_ip: '{{ host_data[inventory_hostname].loopback1_ip }}'
mclag_member_pcs: []
mclag_pc_1: PortChannel100
mclag_peer_ip: '{{ host_data[inventory_hostname].mclag_peer_ip}}'

vtep_name: '{{ host_data[inventory_hostname].vtep_name }}'

