---
collections:
#  - source: https://github.com/ansible-collections/dellemc.enterprise_sonic.git
#    type: git
  - name: dellemc.enterprise_sonic
    version: "*"
    source: https://galaxy.ansible.com/ui/repo/published/dellemc/enterprise_sonic/ 
